name: Model Training CI

on:
  push:
    branches:
      - kernelridge

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Decision Tree model
        run: python train.py

      - name: Run Kernel Ridge model
        run: python train2.py 